### ISSUE TITLE
build woes (mac 10.14)

### ISSUE THREAD

**Issue by d4tocchini** [Aransentin/wasmdemo#1]
thanks for this clever knowledge drop!

proper way to acquire/build `./bufferize` binary?

pyassimp keeps seg faulting when loading the model, not sure where to start with this one...

```
$ ./build.sh
./build.sh: line 10:  7430 Segmentation fault: 11  ./meshconvert.py > model.buf
./build.sh: line 17: ./bufferize: cannot execute binary file
./build.sh: line 18: ./bufferize: cannot execute binary file
...
```

any clues would be appreciated!

**Comment by Aransentin** [comment]
As you might have noticed, I didn't spend too much time in getting the project easily buildable by others...

_bufferize_ shouldn't really have been included as a Linux binary in the project at all. I replaced it with bufferize.c, which you can just build with `clang bufferize.c -o bufferize`.

As for the segmentation fault, I can't really fix bugs in pyassimp 😔. Easiest "solution" would be just to download _model.buf_ from https://aransentin.github.io/cwasm/demo/model.buf and comment out the entire line.

**Comment by justinclift** [comment]
As a general thought for the Assimp segfault, it could be problem that's fixed by using a newer Assimp version, or perhaps even compiling the development code.

Saying that as someone that was considering using Assimp for a server side project a while back, but saw too many similar segfaults from it so didn't pursue that option.  Some of the segfaults **did** seem to be fixed in the latest development code though. :wink:
